### ISSUE TITLE
CSS variables

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#19]
Please move all colors, font-size, font-family definitions to the root element in your CSS

```css
:root {
  --balck-color: #000;
}

an_element {
  background-color: var(---black-color)
}
```
